In [193]:
import numpy as np
import numpy.random as rand

a = rand.sample((10,3))
print(a)
index = (np.abs(a - 0.5)).argmin(axis = 1)
i = 0
while i < 10:
    print(a[i][index[i]])
    i += 1

[[0.51172793 0.28630201 0.11967327]
 [0.95734956 0.4057977  0.2808503 ]
 [0.07398465 0.40928705 0.25197377]
 [0.62729186 0.40555538 0.44699958]
 [0.23670118 0.89965481 0.78871911]
 [0.42483104 0.751308   0.66082593]
 [0.03065707 0.757097   0.44067905]
 [0.10140213 0.42154382 0.9656327 ]
 [0.23378456 0.78903766 0.45393479]
 [0.18493887 0.45268487 0.27439781]]
0.5117279345173057
0.40579770318144837
0.4092870520235703
0.4469995848898678
0.23670118160113762
0.4248310441143367
0.4406790469752916
0.42154382477426566
0.4539347920242651
0.45268487308959393


In [194]:
import numpy as np

a = np.random.random((6,6))*10
print(a)
index = a.argmin(axis = 0)
i = 0
while i < 6:
    print("\n",np.sum(a[i])/a[index[i]][i])
    i += 1

[[0.48790887 3.37056317 0.98514062 3.90432219 3.92301838 4.07878461]
 [4.68102514 6.41026774 1.50219925 5.19249179 4.81150045 8.82936573]
 [7.49743927 6.93804605 4.83608304 3.01229252 1.13130703 2.06001006]
 [7.3464844  8.85158736 0.82901468 9.3839905  2.78322516 7.53278356]
 [1.56261523 7.22178903 9.46495379 5.21637018 2.13295578 6.30398551]
 [8.19511887 2.04575456 6.45120165 9.44183331 7.35105317 5.05287884]]

 34.32964430638888

 15.361984601597607

 30.729465503903363

 12.192403445769823

 28.199833212799533

 18.70759814218283


In [195]:
import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
len = x.shape[0]
x = x.tolist()
i = 0
max = 0
while i < len:
    try:
        i = x.index(0, i, len) + 1
    except:
        break
    if i == len :
        break
    if max < x[i]: 
        max = x[i]
print(max)

5


In [196]:
import numpy as np

x = np.ones(10)
print(x)
index = np.array([0, 1, 2, 3, 5, 5, 5, 8])
j = 0
while j < 8:
    x[index[j]] += 1
    j += 1
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [197]:
import numpy as np

N = 10
a = np.arange(N * N).reshape(N, N)
d = {}
i = 0
while i < 2*N - 1:
    d[i] = []
    i += 1
i = 0
while i < N:
    j = 0
    while j < N:
        d.get(i + j).append(a[i][j])
        j += 1
    i += 1
print(d)

{0: [0], 1: [1, 10], 2: [2, 11, 20], 3: [3, 12, 21, 30], 4: [4, 13, 22, 31, 40], 5: [5, 14, 23, 32, 41, 50], 6: [6, 15, 24, 33, 42, 51, 60], 7: [7, 16, 25, 34, 43, 52, 61, 70], 8: [8, 17, 26, 35, 44, 53, 62, 71, 80], 9: [9, 18, 27, 36, 45, 54, 63, 72, 81, 90], 10: [19, 28, 37, 46, 55, 64, 73, 82, 91], 11: [29, 38, 47, 56, 65, 74, 83, 92], 12: [39, 48, 57, 66, 75, 84, 93], 13: [49, 58, 67, 76, 85, 94], 14: [59, 68, 77, 86, 95], 15: [69, 78, 87, 96], 16: [79, 88, 97], 17: [89, 98], 18: [99]}
